### ISSUE TITLE
Errors while running default benchmark in Clover

### ISSUE THREAD

**Issue by SeKwonLee** [WukLab/pDPM#2]
I am trying to run the default benchmark (mitsume_benchmark_latency) provided in Clover. However, I found several errors from CN. I have attached logs produced from CN.

1. Replication factor
<img width="1134" alt="Screen Shot 2020-10-17 at 12 07 49 PM" src="https://user-images.githubusercontent.com/10057299/96327301-68c5a980-1073-11eb-9f1c-c17a19a59af8.png">

I have solved this error by changing `MITSUME_BENCHMARK_REPLICATION` macro in `mitsume_benchmark.h` from 3 to 1. However, I am not sure if it is correct. Could you check it once?

2. Request for the size over 1048
<img width="924" alt="Screen Shot 2020-10-17 at 12 03 41 PM" src="https://user-images.githubusercontent.com/10057299/96327259-e6d58080-1072-11eb-9fbf-884fd8611fa2.png">

After fixing the first issue (replication factor), the system was blocked somewhere while handling test size 2048.

**Comment by shinyehtsai** [comment]
You can only have one bucket since you have only one MN.

https://github.com/WukLab/pDPM/blob/master/clover/mitsume_con_alloc.cc#L9-L17
Change this part to give you more 2K entries.
The numbers for each size entry have be a monotonically increasing order, the numbers not in increasing order will be ignored.
Therefore, try to use [5, 10, 20, 30, 50, 70, 90, 99] instead of [1, 2, 3, 98, 15, 95, 96, 98]

**Comment by SeKwonLee** [comment]
@shinyehtsai,

Thanks for your reply. After the modifications you suggested, it becomes working well. I will close this issue.
